### ISSUE TITLE
Add 1.20.6-1.21 Support

### ISSUE THREAD

**Issue by Imptovskii** [CraptiCraft-Development/SpeedLimit#1]
**Describe the bug**
Plugin not work on 1.20.6-1.21

**To Reproduce**
Steps to reproduce the behaviour:
- Just use 1.20.6 or 1.21 server software

**Expected behavior**
The plugin works on the latest versions of server software)

**Desktop (please complete the following information):**
 - Server Version: This server is running Paper version 1.21-44-master@8d91b85 (2024-07-04T18:56:20Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
 - Plugin Version: 5.4.7

**Additional context**
```
[13:45:50] [Server thread/INFO]: [SpeedLimit] Enabling SpeedLimit v5.4.7
[13:45:50] [Server thread/ERROR]: Error occurred while enabling SpeedLimit v5.4.7 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at SpeedLimit-5.4.7.jar/me.loving11ish.speedlimit.utils.VersionCheckerUtils.<init>(VersionCheckerUtils.java:12) ~[SpeedLimit-5.4.7.jar:?]
	at SpeedLimit-5.4.7.jar/me.loving11ish.speedlimit.SpeedLimit.onEnable(SpeedLimit.java:46) ~[SpeedLimit-5.4.7.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-44-8d91b85]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-44-8d91b85]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-44-8d91b85]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-44-8d91b85]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:752) ~[paper-1.21.jar:1.21-44-8d91b85]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:514) ~[paper-1.21.jar:1.21-44-8d91b85]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-44-8d91b85]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219) ~[paper-1.21.jar:1.21-44-8d91b85]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-44-8d91b85]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:45:50] [Server thread/INFO]: [SpeedLimit] Disabling SpeedLimit v5.4.7
[13:45:50] [Server thread/INFO]: -------------------------------------------
[13:45:50] [Server thread/INFO]: [SpeedLimit]: Plugin by Loving11ish
[13:45:50] [Server thread/INFO]: [SpeedLimit]: All background tasks disabled successfully!
[13:45:50] [Server thread/INFO]: [SpeedLimit]: Plugin Version 5.4.7
[13:45:50] [Server thread/INFO]: [SpeedLimit]: Plugin shutdown successfully!
[13:45:50] [Server thread/INFO]: [SpeedLimit]: Goodbye
[13:45:50] [Server thread/INFO]: -------------------------------------------
```

**Comment by Loving11ish** [comment]
This is now fixed in the 5.5.0 version.
